package com.helfio.marketplace;

import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class MarketplaceService {
  private final JdbcTemplate jdbc; private final DomainEvents events;
  public MarketplaceService(JdbcTemplate jdbc, DomainEvents events) { this.jdbc = jdbc; this.events = events; }
  private UUID user(Authentication a) { try { return jdbc.queryForObject("SELECT id FROM users WHERE keycloak_subject_id = ? AND account_status = 'ACTIVE'", UUID.class, a.getName()); } catch (Exception e) { throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Account unavailable"); } }
  private static UUID uuid(String value) { try { return UUID.fromString(value); } catch (Exception e) { throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid id"); } }
  private static String text(Map<String,Object> body, String key) { Object v = body.get(key); if (!(v instanceof String s) || s.trim().isEmpty()) throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid " + key); return s.trim(); }
  private static Object value(Map<String,Object> body, String key) { return body.get(key); }
  private Map<String,Object> job(UUID id) {
    var rows = jdbc.queryForList("SELECT j.id,j.customer_user_id,j.category_id,j.title,j.description,j.city,j.postal_code,j.country_code,j.budget_type,j.budget_min,j.budget_max,j.currency,j.preferred_date,j.preferred_time_text,j.status,j.assigned_provider_user_id,j.created_at,j.updated_at,j.assigned_at,j.started_at,j.finished_at,j.completed_at,j.cancelled_at,c.slug category_slug,c.icon category_icon FROM jobs j JOIN categories c ON c.id=j.category_id WHERE j.id=?", id);
    if (rows.isEmpty()) throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Job not found");
    var r = rows.getFirst(); var out = new LinkedHashMap<String,Object>();
    put(out,"id",r.get("id")); put(out,"customerUserId",r.get("customer_user_id")); put(out,"categoryId",r.get("category_id")); put(out,"title",r.get("title")); put(out,"description",r.get("description")); put(out,"city",r.get("city")); put(out,"postalCode",r.get("postal_code")); put(out,"countryCode",r.get("country_code")); put(out,"budgetType",r.get("budget_type")); put(out,"budgetMin",r.get("budget_min")); put(out,"budgetMax",r.get("budget_max")); put(out,"currency",r.get("currency")); put(out,"preferredDate",r.get("preferred_date")); put(out,"preferredTimeText",r.get("preferred_time_text")); put(out,"status",r.get("status")); put(out,"assignedProviderUserId",r.get("assigned_provider_user_id")); put(out,"createdAt",r.get("created_at")); put(out,"updatedAt",r.get("updated_at")); put(out,"assignedAt",r.get("assigned_at")); put(out,"startedAt",r.get("started_at")); put(out,"finishedAt",r.get("finished_at")); put(out,"completedAt",r.get("completed_at")); put(out,"cancelledAt",r.get("cancelled_at"));
    var category = new LinkedHashMap<String,Object>(); category.put("id", r.get("category_id")); category.put("parentId", null); category.put("slug", r.get("category_slug")); category.put("status", "active"); category.put("icon", r.get("category_icon")); category.put("sortOrder", 0); category.put("showInNavigation", false); category.put("showOnHomepage", false); category.put("translations", Map.of()); out.put("category", category); return out;
  }
  private static void put(Map<String,Object> out, String key, Object value) { if (value instanceof LocalDate d) out.put(key,d.toString()); else out.put(key,value); }
  private List<Map<String,Object>> jobsFor(String sql, Object... args) { return jdbc.queryForList(sql,args).stream().map(r -> job((UUID)r.get("id"))).toList(); }
  public List<Map<String,Object>> customerJobs(Authentication a) { return jobsFor("SELECT id FROM jobs WHERE customer_user_id=? ORDER BY updated_at DESC", user(a)); }
  public List<Map<String,Object>> assignedJobs(Authentication a) { return jobsFor("SELECT id FROM jobs WHERE assigned_provider_user_id=? ORDER BY updated_at DESC", user(a)); }
  public List<Map<String,Object>> openJobs(String category, String city) { var sql="SELECT id FROM jobs WHERE status='OPEN'"; var args=new ArrayList<Object>(); if(category!=null&&!category.isBlank()){sql+=" AND category_id=?";args.add(uuid(category));} if(city!=null&&!city.isBlank()){sql+=" AND city ILIKE ?";args.add("%"+city+"%");} sql+=" ORDER BY updated_at DESC LIMIT 100"; return jobsFor(sql,args.toArray()); }
  @Transactional public Map<String,Object> createJob(Authentication a, Map<String,Object> b) { UUID customer=user(a), category=uuid(text(b,"categoryId")); if(jdbc.queryForObject("SELECT count(*) FROM categories WHERE id=? AND status='active'",Long.class,category)==0) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid active category"); var id=UUID.randomUUID(); jdbc.update("INSERT INTO jobs(id,customer_user_id,category_id,title,description,city,postal_code,country_code,budget_type,budget_min,budget_max,currency,preferred_date,preferred_time_text) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,customer,category,text(b,"title"),text(b,"description"),text(b,"city"),value(b,"postalCode"),text(b,"countryCode").toUpperCase(),text(b,"budgetType"),value(b,"budgetMin"),value(b,"budgetMax"),text(b,"currency").toUpperCase(),value(b,"preferredDate"),value(b,"preferredTimeText")); events.append("job.created",id,Map.of("customerUserId",customer.toString(),"recipientUserIds",List.of(customer.toString()))); return job(id); }
  @Transactional public Map<String,Object> updateJob(Authentication a, UUID id, Map<String,Object> b) { UUID customer=user(a); if(!Objects.equals(jdbc.queryForObject("SELECT customer_user_id FROM jobs WHERE id=?",UUID.class,id),customer)) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Job ownership required"); var allowed=List.of("title","description","city","postalCode","countryCode","budgetType","budgetMin","budgetMax","currency","preferredDate","preferredTimeText"); for(var key:allowed) if(b.containsKey(key)) jdbc.update("UPDATE jobs SET "+snake(key)+"=?,updated_at=now() WHERE id=?",b.get(key),id); return job(id); }
  private static String snake(String s){return s.replaceAll("([A-Z])","_$1").toLowerCase();}
  @Transactional public Map<String,Object> transition(Authentication a, UUID id, String action) { UUID customer=user(a); var current=jdbc.queryForMap("SELECT status,customer_user_id FROM jobs WHERE id=?",id); if(!customer.equals(current.get("customer_user_id"))) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Job ownership required"); String from=String.valueOf(current.get("status")); String to=switch(action){case "publish"->"OPEN";case "cancel"->"CANCELLED";case "confirm"->"COMPLETED";default->throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Not found");}; if(to.equals("OPEN")&&!from.equals("DRAFT")||to.equals("CANCELLED")&&!Set.of("DRAFT","OPEN","ASSIGNED").contains(from)||to.equals("COMPLETED")&&!from.equals("AWAITING_CONFIRMATION")) throw new ResponseStatusException(HttpStatus.CONFLICT,"Invalid job transition"); var updated=jdbc.update("UPDATE jobs SET status=?,cancelled_at=CASE WHEN ?='CANCELLED' THEN now() ELSE cancelled_at END,completed_at=CASE WHEN ?='COMPLETED' THEN now() ELSE completed_at END,updated_at=now() WHERE id=? AND status=?",to,to,to,id,from); if(updated!=1) throw new ResponseStatusException(HttpStatus.CONFLICT,"Invalid job transition"); events.append("job."+(to.equals("OPEN")?"published":to.equals("COMPLETED")?"completed":"cancelled"),id,Map.of("customerUserId",customer.toString(),"recipientUserIds",List.of(customer.toString()))); return job(id); }
  @Transactional public Map<String,Object> providerTransition(Authentication a, UUID id, String action) { UUID provider=user(a); String to=action.equals("start")?"IN_PROGRESS":"AWAITING_CONFIRMATION"; String from=action.equals("start")?"ASSIGNED":"IN_PROGRESS"; var row=jdbc.queryForMap("SELECT customer_user_id FROM jobs WHERE id=? AND assigned_provider_user_id=? AND status=? FOR UPDATE",id,provider,from); jdbc.update("UPDATE jobs SET status=?,started_at=CASE WHEN ?='IN_PROGRESS' THEN now() ELSE started_at END,finished_at=CASE WHEN ?='AWAITING_CONFIRMATION' THEN now() ELSE finished_at END,updated_at=now() WHERE id=?",to,to,to,id); events.append("job."+(to.equals("IN_PROGRESS")?"started":"awaiting_confirmation"),id,Map.of("providerUserId",provider.toString(),"recipientUserIds",List.of(String.valueOf(row.get("customer_user_id"))))); return job(id); }
  public List<Map<String,Object>> offersForJob(Authentication a, UUID jobId) { UUID customer=user(a); if(!customer.equals(jdbc.queryForObject("SELECT customer_user_id FROM jobs WHERE id=?",UUID.class,jobId))) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Job ownership required"); return jdbc.queryForList("SELECT id,job_id,provider_user_id,price,currency,message,estimated_duration,available_from,status,created_at,updated_at FROM offers WHERE job_id=? ORDER BY created_at",jobId); }
  public List<Map<String,Object>> offersForProvider(Authentication a) { return jdbc.queryForList("SELECT id,job_id,provider_user_id,price,currency,message,estimated_duration,available_from,status,created_at,updated_at FROM offers WHERE provider_user_id=? ORDER BY updated_at DESC",user(a)); }
  @Transactional public Map<String,Object> createOffer(Authentication a, UUID jobId, Map<String,Object> b) { UUID provider=user(a), id=UUID.randomUUID(); var customer=jdbc.queryForObject("SELECT customer_user_id FROM jobs WHERE id=? AND status='OPEN' AND customer_user_id<>?",UUID.class,jobId,provider); jdbc.update("INSERT INTO offers(id,job_id,provider_user_id,price,currency,message,estimated_duration,available_from) VALUES (?,?,?,?,?,?,?,?)",id,jobId,provider,b.get("price"),text(b,"currency").toUpperCase(),text(b,"message"),value(b,"estimatedDuration"),value(b,"availableFrom")); events.append("offer.created",id,Map.of("jobId",jobId.toString(),"providerUserId",provider.toString(),"customerUserId",customer.toString(),"recipientUserIds",List.of(customer.toString()))); return jdbc.queryForMap("SELECT id,job_id,provider_user_id,price,currency,message,estimated_duration,available_from,status,created_at,updated_at FROM offers WHERE id=?",id); }
  @Transactional public Map<String,Object> offerAction(Authentication a, UUID id, String action) { UUID customer=user(a); var offer=jdbc.queryForMap("SELECT o.job_id,o.provider_user_id,j.customer_user_id FROM offers o JOIN jobs j ON j.id=o.job_id WHERE o.id=? AND j.customer_user_id=? FOR UPDATE",id,customer); if(action.equals("accept")){jdbc.queryForMap("SELECT id FROM jobs WHERE id=? AND status='OPEN' FOR UPDATE",offer.get("job_id")); jdbc.update("UPDATE offers SET status='ACCEPTED',updated_at=now() WHERE id=? AND status='PENDING'",id); jdbc.update("UPDATE offers SET status='REJECTED',updated_at=now() WHERE job_id=? AND id<>? AND status='PENDING'",offer.get("job_id"),id); jdbc.update("UPDATE jobs SET status='ASSIGNED',assigned_provider_user_id=?,assigned_at=now(),updated_at=now() WHERE id=? AND status='OPEN'",offer.get("provider_user_id"),offer.get("job_id")); events.append("offer.accepted",id,Map.of("recipientUserIds",List.of(String.valueOf(offer.get("provider_user_id"))))); events.append("job.assigned",(UUID)offer.get("job_id"),Map.of("recipientUserIds",List.of(String.valueOf(offer.get("provider_user_id"))));} else {jdbc.update("UPDATE offers SET status=? WHERE id=? AND status='PENDING'",action.equals("reject")?"REJECTED":"WITHDRAWN",id);} return jdbc.queryForMap("SELECT id,job_id,provider_user_id,price,currency,message,estimated_duration,available_from,status,created_at,updated_at FROM offers WHERE id=?",id); }
  @Transactional public Map<String,Object> withdraw(Authentication a, UUID id) { UUID provider=user(a); jdbc.update("UPDATE offers SET status='WITHDRAWN',updated_at=now() WHERE id=? AND provider_user_id=? AND status='PENDING'",id,provider); return jdbc.queryForMap("SELECT id,job_id,provider_user_id,price,currency,message,estimated_duration,available_from,status,created_at,updated_at FROM offers WHERE id=?",id); }
  @Transactional public Map<String,Object> updateOffer(Authentication a, UUID id, Map<String,Object> b) { UUID provider=user(a); int changed=jdbc.update("UPDATE offers SET price=COALESCE(?,price),currency=COALESCE(?,currency),message=COALESCE(?,message),estimated_duration=COALESCE(?,estimated_duration),available_from=COALESCE(?,available_from),updated_at=now() WHERE id=? AND provider_user_id=? AND status='PENDING'",b.get("price"),b.get("currency"),b.get("message"),b.get("estimatedDuration"),b.get("availableFrom"),id,provider); if(changed!=1) throw new ResponseStatusException(HttpStatus.CONFLICT,"Offer cannot be edited"); return jdbc.queryForMap("SELECT id,job_id,provider_user_id,price,currency,message,estimated_duration,available_from,status,created_at,updated_at FROM offers WHERE id=?",id); }
  @Transactional public Map<String,Object> review(Authentication a, UUID jobId, Map<String,Object> b) { UUID customer=user(a); var provider=jdbc.queryForObject("SELECT assigned_provider_user_id FROM jobs WHERE id=? AND customer_user_id=? AND status='COMPLETED'",UUID.class,jobId,customer); UUID id=UUID.randomUUID(); jdbc.update("INSERT INTO reviews(id,job_id,customer_user_id,provider_user_id,rating,comment) VALUES (?,?,?,?,?,?)",id,jobId,customer,provider,b.get("rating"),b.get("comment")); events.append("review.created",id,Map.of("recipientUserIds",List.of(provider.toString()))); return jdbc.queryForMap("SELECT id,job_id,provider_user_id,rating,comment,created_at,updated_at FROM reviews WHERE id=?",id); }
}
