import { pool } from './db.js'
import type { CategoryRow } from './categories.js'
import type { UserAccount } from './db.js'

export interface AdminListQuery { search: string; status: string | null; page: number; pageSize: number }
export interface AdminPage<T> { items: T[]; page: number; pageSize: number; total: number; hasNext: boolean }
export interface AdminMetrics { totalUsers: number; customers: number; providers: number; activeJobs: number; completedJobs: number; reviews: number; recentActivity: AuditEntry[] }
export interface AuditEntry { id: string; adminUserId: string; action: string; targetType: string; targetId: string; before: unknown; after: unknown; createdAt: string }
export interface AdminUser extends UserAccount { roles: string[] }
export interface AdminProvider { userId: string; displayName: string | null; email: string | null; accountStatus: string; verificationStatus: string; visibility: string; services: string[]; rating: number | null; reviewCount: number }
export interface AdminJob { id: string; title: string; status: string; customerUserId: string; customerName: string | null; providerUserId: string | null; providerName: string | null; categoryId: string; categorySlug: string; createdAt: string; updatedAt: string }
export interface AdminReview { id: string; jobId: string; providerUserId: string; providerName: string | null; rating: number; comment: string | null; moderationStatus: string; createdAt: string }
export interface CategoryInput { parentId: string | null; slug: string; status: 'active' | 'inactive'; icon: string | null; sortOrder: number; showInNavigation: boolean; showOnHomepage: boolean; translations: Record<string, { name: string; description: string | null }> }

function page<T>(items: T[], total: number, query: AdminListQuery): AdminPage<T> { return { items, page: query.page, pageSize: query.pageSize, total, hasNext: query.page * query.pageSize < total } }
function like(search: string) { return `%${search.replace(/[\\%_]/g, (value) => `\\${value}`)}%` }
function mapAudit(row: Record<string, unknown>): AuditEntry { return { id: String(row.id), adminUserId: String(row.adminUserId), action: String(row.action), targetType: String(row.targetType), targetId: String(row.targetId), before: row.before, after: row.after, createdAt: String(row.createdAt) } }
const categorySelect = `SELECT c.id, c.parent_id AS "parentId", c.slug, c.status, c.icon, c.sort_order AS "sortOrder", c.show_in_navigation AS "showInNavigation", c.show_on_homepage AS "showOnHomepage", c.created_at AS "createdAt", c.updated_at AS "updatedAt", COALESCE(jsonb_object_agg(t.locale, jsonb_build_object('name', t.name, 'description', t.description)) FILTER (WHERE t.locale IS NOT NULL), '{}') AS translations FROM categories c LEFT JOIN category_translations t ON t.category_id = c.id`

export async function adminDashboard(): Promise<AdminMetrics> {
  const [users, customers, providers, activeJobs, completedJobs, reviews, activity] = await Promise.all([
    pool.query<{ count: string }>('SELECT count(*)::int AS count FROM users'), pool.query<{ count: string }>("SELECT count(*)::int AS count FROM users u WHERE EXISTS (SELECT 1 FROM jobs j WHERE j.customer_user_id = u.id)"), pool.query<{ count: string }>('SELECT count(*)::int AS count FROM provider_profiles'), pool.query<{ count: string }>("SELECT count(*)::int AS count FROM jobs WHERE status IN ('OPEN','ASSIGNED','IN_PROGRESS','AWAITING_CONFIRMATION')"), pool.query<{ count: string }>("SELECT count(*)::int AS count FROM jobs WHERE status = 'COMPLETED'"), pool.query<{ count: string }>("SELECT count(*)::int AS count FROM reviews WHERE moderation_status = 'VISIBLE'"), auditLog({ page: 1, pageSize: 8 }),
  ])
  return { totalUsers: users.rows[0].count as unknown as number, customers: customers.rows[0].count as unknown as number, providers: providers.rows[0].count as unknown as number, activeJobs: activeJobs.rows[0].count as unknown as number, completedJobs: completedJobs.rows[0].count as unknown as number, reviews: reviews.rows[0].count as unknown as number, recentActivity: activity.items }
}

export async function listUsers(query: AdminListQuery): Promise<AdminPage<AdminUser>> {
  const filters: string[] = []; const values: unknown[] = []
  if (query.search) { values.push(like(query.search)); filters.push(`(u.id::text ILIKE $${values.length} OR u.email ILIKE $${values.length} OR u.display_name ILIKE $${values.length} OR u.keycloak_subject_id ILIKE $${values.length})`) }
  if (query.status) { values.push(query.status); filters.push(`u.account_status = $${values.length}`) }
  const where = filters.length ? `WHERE ${filters.join(' AND ')}` : ''
  const total = await pool.query<{ count: string }>(`SELECT count(*)::int AS count FROM users u ${where}`, values)
  values.push(query.pageSize, (query.page - 1) * query.pageSize)
  const result = await pool.query(`SELECT u.id, u.keycloak_subject_id AS "keycloakSubjectId", u.email, u.display_name AS "displayName", u.preferred_locale AS "preferredLocale", u.account_status AS "accountStatus", u.created_at AS "createdAt", u.updated_at AS "updatedAt", ARRAY_REMOVE(ARRAY[CASE WHEN EXISTS (SELECT 1 FROM jobs j WHERE j.customer_user_id = u.id) THEN 'CUSTOMER' END, CASE WHEN EXISTS (SELECT 1 FROM provider_profiles p WHERE p.user_id = u.id) THEN 'PROVIDER' END], NULL) AS roles FROM users u ${where} ORDER BY u.created_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values)
  return page(result.rows.map((row) => ({ ...row, roles: row.roles ?? [] }) as AdminUser), Number(total.rows[0].count), query)
}

export async function listProviders(query: AdminListQuery): Promise<AdminPage<AdminProvider>> {
  const values: unknown[] = []; const filters = ['1=1']; if (query.search) { values.push(like(query.search)); filters.push(`(u.id::text ILIKE $${values.length} OR u.email ILIKE $${values.length} OR p.display_name ILIKE $${values.length})`) } if (query.status) { values.push(query.status); filters.push(`u.account_status = $${values.length}`) }
  const where = filters.join(' AND '); const total = await pool.query<{ count: string }>(`SELECT count(*)::int AS count FROM provider_profiles p JOIN users u ON u.id = p.user_id WHERE ${where}`, values); values.push(query.pageSize, (query.page - 1) * query.pageSize)
  const result = await pool.query(`SELECT p.user_id AS "userId", p.display_name AS "displayName", u.email, u.account_status AS "accountStatus", p.verification_status AS "verificationStatus", p.visibility, COALESCE(array_agg(c.slug) FILTER (WHERE c.slug IS NOT NULL), '{}') AS services, ROUND(AVG(r.rating)::numeric, 1)::float AS rating, count(r.id)::int AS "reviewCount" FROM provider_profiles p JOIN users u ON u.id = p.user_id LEFT JOIN provider_services ps ON ps.provider_user_id = p.user_id LEFT JOIN categories c ON c.id = ps.category_id LEFT JOIN reviews r ON r.provider_user_id = p.user_id AND r.moderation_status = 'VISIBLE' WHERE ${where} GROUP BY p.user_id, p.display_name, p.updated_at, u.email, u.account_status, p.verification_status, p.visibility ORDER BY p.updated_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values)
  return page(result.rows as AdminProvider[], Number(total.rows[0].count), query)
}

export async function listJobs(query: AdminListQuery): Promise<AdminPage<AdminJob>> {
  const values: unknown[] = []; const filters = ['1=1']; if (query.search) { values.push(like(query.search)); filters.push(`(j.id::text ILIKE $${values.length} OR j.title ILIKE $${values.length} OR j.description ILIKE $${values.length} OR c.slug ILIKE $${values.length})`) } if (query.status) { values.push(query.status); filters.push(`j.status = $${values.length}`) }
  const where = filters.join(' AND '); const total = await pool.query<{ count: string }>(`SELECT count(*)::int AS count FROM jobs j JOIN categories c ON c.id = j.category_id WHERE ${where}`, values); values.push(query.pageSize, (query.page - 1) * query.pageSize)
  const result = await pool.query(`SELECT j.id, j.title, j.status, j.customer_user_id AS "customerUserId", cu.display_name AS "customerName", j.assigned_provider_user_id AS "providerUserId", pu.display_name AS "providerName", j.category_id AS "categoryId", c.slug AS "categorySlug", j.created_at AS "createdAt", j.updated_at AS "updatedAt" FROM jobs j JOIN categories c ON c.id = j.category_id JOIN users cu ON cu.id = j.customer_user_id LEFT JOIN users pu ON pu.id = j.assigned_provider_user_id WHERE ${where} ORDER BY j.updated_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values)
  return page(result.rows as AdminJob[], Number(total.rows[0].count), query)
}

export async function listReviews(query: AdminListQuery): Promise<AdminPage<AdminReview>> {
  const values: unknown[] = []; const filters = ['1=1']; if (query.search) { values.push(like(query.search)); filters.push(`(r.id::text ILIKE $${values.length} OR r.comment ILIKE $${values.length} OR j.title ILIKE $${values.length} OR p.display_name ILIKE $${values.length})`) } if (query.status) { values.push(query.status); filters.push(`r.moderation_status = $${values.length}`) }
  const where = filters.join(' AND '); const total = await pool.query<{ count: string }>(`SELECT count(*)::int AS count FROM reviews r JOIN jobs j ON j.id = r.job_id JOIN users p ON p.id = r.provider_user_id WHERE ${where}`, values); values.push(query.pageSize, (query.page - 1) * query.pageSize)
  const result = await pool.query(`SELECT r.id, r.job_id AS "jobId", r.provider_user_id AS "providerUserId", p.display_name AS "providerName", r.rating, r.comment, r.moderation_status AS "moderationStatus", r.created_at AS "createdAt" FROM reviews r JOIN jobs j ON j.id = r.job_id JOIN users p ON p.id = r.provider_user_id WHERE ${where} ORDER BY r.created_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values)
  return page(result.rows as AdminReview[], Number(total.rows[0].count), query)
}

export async function listCategories(): Promise<CategoryRow[]> { const result = await pool.query<CategoryRow>(`${categorySelect} GROUP BY c.id ORDER BY c.sort_order, c.slug`); return result.rows }
export async function createCategory(input: CategoryInput): Promise<CategoryRow> { const client = await pool.connect(); try { await client.query('BEGIN'); const result = await client.query<CategoryRow>('INSERT INTO categories (parent_id, slug, status, icon, sort_order, show_in_navigation, show_on_homepage) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id', [input.parentId, input.slug, input.status, input.icon, input.sortOrder, input.showInNavigation, input.showOnHomepage]); const id = result.rows[0].id; for (const [locale, translation] of Object.entries(input.translations)) await client.query('INSERT INTO category_translations (category_id, locale, name, description) VALUES ($1,$2,$3,$4)', [id, locale, translation.name, translation.description]); await client.query('COMMIT'); return (await listCategories()).find((category) => category.id === id)! } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } }
export async function updateCategory(id: string, input: CategoryInput): Promise<CategoryRow> { const client = await pool.connect(); try { await client.query('BEGIN'); await client.query('UPDATE categories SET parent_id=$2, slug=$3, status=$4, icon=$5, sort_order=$6, show_in_navigation=$7, show_on_homepage=$8, updated_at=now() WHERE id=$1', [id, input.parentId, input.slug, input.status, input.icon, input.sortOrder, input.showInNavigation, input.showOnHomepage]); await client.query('DELETE FROM category_translations WHERE category_id=$1', [id]); for (const [locale, translation] of Object.entries(input.translations)) await client.query('INSERT INTO category_translations (category_id, locale, name, description) VALUES ($1,$2,$3,$4)', [id, locale, translation.name, translation.description]); await client.query('COMMIT'); return (await listCategories()).find((category) => category.id === id)! } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } }
export async function deleteCategory(id: string): Promise<void> { const result = await pool.query('DELETE FROM categories WHERE id=$1', [id]); if (!result.rowCount) throw new Error('Category not found') }
export async function updateUserStatus(id: string, status: string): Promise<AdminUser> { const result = await pool.query(`UPDATE users SET account_status=$2, updated_at=now() WHERE id=$1 RETURNING id, keycloak_subject_id AS "keycloakSubjectId", email, display_name AS "displayName", preferred_locale AS "preferredLocale", account_status AS "accountStatus", created_at AS "createdAt", updated_at AS "updatedAt", ARRAY[]::text[] AS roles`, [id, status]); if (!result.rows[0]) throw new Error('User not found'); return result.rows[0] as AdminUser }
export async function updateProviderStatus(id: string, input: { accountStatus?: string; verificationStatus?: string }): Promise<AdminProvider> { if (input.accountStatus) await pool.query('UPDATE users SET account_status=$2, updated_at=now() WHERE id=$1', [id, input.accountStatus]); if (input.verificationStatus) await pool.query('UPDATE provider_profiles SET verification_status=$2, updated_at=now() WHERE user_id=$1', [id, input.verificationStatus]); const result = await listProviders({ search: id, status: null, page: 1, pageSize: 1 }); if (!result.items[0]) throw new Error('Provider not found'); return result.items[0] }
export async function moderateReview(id: string, status: 'VISIBLE' | 'HIDDEN'): Promise<AdminReview> { const result = await pool.query(`UPDATE reviews SET moderation_status=$2, updated_at=now() WHERE id=$1 RETURNING id`, [id, status]); if (!result.rows[0]) throw new Error('Review not found'); const reviews = await listReviews({ search: id, status: null, page: 1, pageSize: 1 }); if (!reviews.items[0]) throw new Error('Review not found'); return reviews.items[0] }
export async function auditLog(query: { page: number; pageSize: number }): Promise<AdminPage<AuditEntry>> { const total = await pool.query<{ count: string }>('SELECT count(*)::int AS count FROM admin_audit_log'); const result = await pool.query(`SELECT id, admin_user_id AS "adminUserId", action, target_type AS "targetType", target_id AS "targetId", before_data AS before, after_data AS after, created_at AS "createdAt" FROM admin_audit_log ORDER BY created_at DESC LIMIT $1 OFFSET $2`, [query.pageSize, (query.page - 1) * query.pageSize]); return page(result.rows.map(mapAudit), Number(total.rows[0].count), { ...query, search: '', status: null }) }
export async function recordAudit(adminUserId: string, action: string, targetType: string, targetId: string, before: unknown, after: unknown) { await pool.query('INSERT INTO admin_audit_log (admin_user_id, action, target_type, target_id, before_data, after_data) VALUES ($1,$2,$3,$4,$5,$6)', [adminUserId, action, targetType, targetId, before ?? null, after ?? null]) }
export async function getSettings(): Promise<Record<string, unknown>> { const result = await pool.query<{ key: string; value: unknown }>('SELECT key, value FROM admin_settings ORDER BY key'); return Object.fromEntries(result.rows.map((row) => [row.key, row.value])) }
export async function updateSettings(adminUserId: string, values: Record<string, unknown>) { for (const [key, value] of Object.entries(values)) await pool.query('INSERT INTO admin_settings (key,value,updated_by) VALUES ($1,$2,$3) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_by=EXCLUDED.updated_by, updated_at=now()', [key, value, adminUserId]); return getSettings() }
