<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getAccessToken, useAuth } from '../auth/keycloak'
import { useI18n } from 'vue-i18n'

interface Page { items: Record<string, unknown>[]; total: number; hasNext: boolean }
interface Category { id: string; parentId: string | null; slug: string; status: string; icon: string | null; sortOrder: number; showInNavigation: boolean; showOnHomepage: boolean; translations: Record<string, { name: string; description: string | null }> }
const { t } = useI18n(); const { authenticated, hasRole } = useAuth()
const tab = ref('dashboard'); const search = ref(''); const status = ref(''); const loading = ref(false); const error = ref(''); const data = ref<Page | null>(null); const categories = ref<Category[]>([]); const metrics = ref<Record<string, unknown> | null>(null); const settings = ref<Record<string, unknown>>({})
const editing = ref<Category | null>(null)
const emptyCategory = (): Category => ({ id: '', parentId: null, slug: '', status: 'active', icon: null, sortOrder: 0, showInNavigation: false, showOnHomepage: false, translations: Object.fromEntries(['en', 'de', 'sq', 'tr'].map((locale) => [locale, { name: '', description: null }])) })
const title = computed(() => tab.value === 'dashboard' ? t('admin.dashboard') : t(`admin.${tab.value}`))
async function api(path: string, init?: RequestInit) { const token = await getAccessToken(); if (!token) throw new Error(t('admin.authRequired')); const response = await fetch(path, { ...init, headers: { 'content-type': 'application/json', Authorization: `Bearer ${token}`, ...(init?.headers ?? {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || t('admin.requestFailed')); return payload.data }
async function load() { if (!authenticated.value || !hasRole('ADMIN')) return; loading.value = true; error.value = ''; try { if (tab.value === 'dashboard') metrics.value = await api('/api/v1/admin/dashboard'); else if (tab.value === 'categories') categories.value = await api('/api/v1/admin/categories'); else if (tab.value === 'settings') settings.value = await api('/api/v1/admin/settings'); else data.value = await api(`/api/v1/admin/${tab.value}?search=${encodeURIComponent(search.value)}&status=${encodeURIComponent(status.value)}`) } catch (cause) { error.value = cause instanceof Error ? cause.message : t('admin.requestFailed') } finally { loading.value = false } }
function selectTab(next: string) { tab.value = next; data.value = null; void load() }
function editCategory(category: Category) { editing.value = JSON.parse(JSON.stringify(category)) as Category }
async function saveCategory() { if (!editing.value) return; try { const method = editing.value.id ? 'PATCH' : 'POST'; const path = `/api/v1/admin/categories${editing.value.id ? `/${editing.value.id}` : ''}`; await api(path, { method, body: JSON.stringify(editing.value) }); editing.value = null; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : t('admin.requestFailed') } }
async function moderate(id: string, next: string) { try { await api(`/api/v1/admin/reviews/${id}/moderation`, { method: 'PATCH', body: JSON.stringify({ status: next }) }); await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : t('admin.requestFailed') } }
function display(value: unknown) { return value === null || value === undefined || value === '' ? '-' : String(value) }
onMounted(() => void load())
</script>

<template>
  <main class="admin-shell" v-if="authenticated && hasRole('ADMIN')">
    <aside class="admin-sidebar"><div class="admin-brand">Helfio <span>ADMIN</span></div><nav><button v-for="item in ['dashboard','users','providers','jobs','reviews','categories','audit-log','settings']" :key="item" :class="{ active: tab === item }" type="button" @click="selectTab(item)">{{ t(`admin.${item}`) }}</button></nav></aside>
    <section class="admin-content"><header class="admin-topbar"><div><span class="section-kicker">{{ t('admin.workspace') }}</span><h1>{{ title }}</h1></div><button class="admin-refresh" type="button" @click="load">{{ t('admin.refresh') }}</button></header>
      <p v-if="error" class="admin-error" role="alert" aria-live="assertive">{{ error }}</p><div v-if="loading" class="admin-state" role="status" aria-live="polite">{{ t('admin.loading') }}</div>
      <template v-else-if="tab === 'dashboard' && metrics"><div class="admin-metrics"><article v-for="item in [['totalUsers','admin.totalUsers'],['customers','admin.customers'],['providers','admin.providers'],['activeJobs','admin.activeJobs'],['completedJobs','admin.completedJobs'],['reviews','admin.reviews']]" :key="item[0]"><span>{{ t(item[1]) }}</span><strong>{{ display(metrics[item[0]]) }}</strong></article></div><section class="admin-section"><h2>{{ t('admin.recentActivity') }}</h2><div v-if="!(metrics.recentActivity as unknown[]).length" class="admin-state">{{ t('admin.empty') }}</div><table v-else><tbody><tr v-for="item in metrics.recentActivity as Record<string, unknown>[]" :key="String(item.id)"><td>{{ display(item.action) }}</td><td>{{ display(item.targetType) }} / {{ display(item.targetId) }}</td><td>{{ display(item.createdAt) }}</td></tr></tbody></table></section></template>
      <template v-else-if="tab === 'categories'"><div class="admin-toolbar"><button class="admin-primary" type="button" @click="editing = emptyCategory()">{{ t('admin.createCategory') }}</button></div><div v-if="!categories.length" class="admin-state">{{ t('admin.empty') }}</div><table v-else><thead><tr><th>{{ t('admin.name') }}</th><th>{{ t('admin.slug') }}</th><th>{{ t('admin.status') }}</th><th>{{ t('admin.order') }}</th><th></th></tr></thead><tbody><tr v-for="category in categories" :key="category.id"><td>{{ category.translations.en?.name || category.slug }}</td><td>{{ category.slug }}</td><td>{{ category.status }}</td><td>{{ category.sortOrder }}</td><td><button class="admin-link" type="button" @click="editCategory(category)">{{ t('admin.edit') }}</button></td></tr></tbody></table></template>
      <template v-else-if="tab !== 'dashboard' && data"><div class="admin-toolbar"><input v-model="search" :placeholder="t('admin.search')" @keyup.enter="load"><select v-model="status" @change="load"><option value="">{{ t('admin.allStatuses') }}</option><option value="ACTIVE">ACTIVE</option><option value="OPEN">OPEN</option><option value="VISIBLE">VISIBLE</option><option value="HIDDEN">HIDDEN</option></select><button class="admin-primary" type="button" @click="load">{{ t('admin.search') }}</button></div><div v-if="!data.items.length" class="admin-state">{{ t('admin.empty') }}</div><table v-else><thead><tr><th v-for="key in Object.keys(data.items[0]).slice(0, 6)" :key="key">{{ key }}</th></tr></thead><tbody><tr v-for="item in data.items" :key="String(item.id || item.userId)"><td v-for="key in Object.keys(data.items[0]).slice(0, 6)" :key="key">{{ display(Array.isArray(item[key]) ? (item[key] as unknown[]).join(', ') : item[key]) }}<button v-if="tab === 'reviews' && key === 'moderationStatus'" class="admin-link" type="button" @click="moderate(String(item.id), item[key] === 'HIDDEN' ? 'VISIBLE' : 'HIDDEN')">{{ item[key] === 'HIDDEN' ? t('admin.show') : t('admin.hide') }}</button></td></tr></tbody></table></template>
      <div v-else class="admin-state">{{ t('admin.empty') }}</div>
    </section>
    <div v-if="editing" class="admin-modal"><form @submit.prevent="saveCategory"><h2>{{ editing.id ? t('admin.edit') : t('admin.createCategory') }}</h2><label>{{ t('admin.slug') }}<input v-model="editing.slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"></label><label>{{ t('admin.parent') }}<select v-model="editing.parentId"><option :value="null">{{ t('admin.none') }}</option><option v-for="category in categories.filter((item) => item.id !== editing?.id)" :key="category.id" :value="category.id">{{ category.slug }}</option></select></label><label>{{ t('admin.status') }}<select v-model="editing.status"><option value="active">{{ t('admin.active') }}</option><option value="inactive">{{ t('admin.inactive') }}</option></select></label><label>{{ t('admin.order') }}<input v-model.number="editing.sortOrder" type="number"></label><label class="admin-check"><input v-model="editing.showInNavigation" type="checkbox"> {{ t('admin.navigation') }}</label><label class="admin-check"><input v-model="editing.showOnHomepage" type="checkbox"> {{ t('admin.homepage') }}</label><div v-for="locale in ['en','de','sq','tr']" :key="locale" class="translation"><strong>{{ locale.toUpperCase() }}</strong><input v-model="editing.translations[locale].name" :placeholder="t('admin.name')" required><textarea v-model="editing.translations[locale].description" :placeholder="t('admin.description')" /></div><div class="admin-actions"><button type="button" @click="editing = null">{{ t('admin.cancel') }}</button><button class="admin-primary" type="submit">{{ t('admin.save') }}</button></div></form></div>
  </main>
  <main v-else class="admin-denied"><h1>{{ t('admin.accessDenied') }}</h1><p>{{ t('admin.adminOnly') }}</p></main>
</template>
