<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { getAccessToken } from '../auth/keycloak'
const { t } = useI18n()
interface Job { id: string; title: string; description: string; city: string; currency: string; budgetMin: number | null; budgetMax: number | null; status?: string; category: { translations: Record<string, { name: string }> } }
interface Offer { id: string; jobId: string; price: number; currency: string; message: string; estimatedDuration: string | null; availableFrom: string | null; status: string }
const jobs = ref<Job[]>([]); const assignedJobs = ref<Job[]>([]); const selected = ref<Job | null>(null); const offers = ref<Offer[]>([]); const message = ref(''); const saving = ref(false)
const form = reactive({ price: null as number | null, currency: 'EUR', message: '', estimatedDuration: '', availableFrom: '' })
async function api(path: string, init?: RequestInit) { const token = await getAccessToken(); return fetch(path, { ...init, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}), ...(init?.headers ?? {}) } }) }
async function refresh() { const [openResponse, assignedResponse] = await Promise.all([api('/api/v1/provider/jobs'), api('/api/v1/provider/jobs/assigned')]); if (openResponse.ok) jobs.value = (await openResponse.json()).data; if (assignedResponse.ok) assignedJobs.value = (await assignedResponse.json()).data }
async function lifecycle(job: Job, action: 'start' | 'finish' | 'complete') { const endpoint = action === 'complete' ? 'finish' : action; const response = await api(`/api/v1/provider/jobs/${job.id}/${endpoint}`, { method: 'POST' }); if (response.ok) await refresh() }
async function select(job: Job) { selected.value = job; const response = await api('/api/v1/provider/offers'); offers.value = response.ok ? (await response.json()).data.filter((offer: Offer) => offer.jobId === job.id) : [] }
async function submit() { if (!selected.value) return; saving.value = true; const editing = offers.value.find((offer) => offer.id === editingId.value); const response = await api(editing ? `/api/v1/offers/${editing.id}` : `/api/v1/jobs/${selected.value.id}/offers`, { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, estimatedDuration: form.estimatedDuration || null, availableFrom: form.availableFrom || null }) }); message.value = response.ok ? t(editing ? 'offers.updated' : 'offers.submitted') : t(editing ? 'offers.updateError' : 'offers.submitError'); saving.value = false; if (response.ok) { await select(selected.value); editingId.value = null; Object.assign(form, { price: null, message: '', estimatedDuration: '', availableFrom: '' }) } }
const editingId = ref<string | null>(null)
function edit(offer: Offer) { editingId.value = offer.id; Object.assign(form, { price: offer.price, currency: offer.currency, message: offer.message, estimatedDuration: offer.estimatedDuration ?? '', availableFrom: offer.availableFrom ?? '' }) }
async function withdraw(offer: Offer) { const response = await api(`/api/v1/offers/${offer.id}/withdraw`, { method: 'POST' }); if (response.ok && selected.value) await select(selected.value) }
onMounted(refresh)
</script>
<template>
  <section class="content-section container offers-panel"><div class="section-heading"><div><span class="section-kicker">{{ t('offers.providerKicker') }}</span><h2>{{ t('offers.providerTitle') }}</h2><p>{{ t('offers.providerDescription') }}</p></div></div><div class="assigned-jobs"><h3>{{ t('offers.assignedTitle') }}</h3><p v-if="!assignedJobs.length" class="job-empty">{{ t('offers.noAssignedJobs') }}</p><article v-for="job in assignedJobs" :key="job.id" class="offer-row"><span><strong>{{ job.title }}</strong> · {{ t(`jobs.status.${job.status?.toLowerCase()}`) }}<small>{{ job.city }}</small></span><span><button v-if="job.status === 'ASSIGNED'" class="header-cta" type="button" @click="lifecycle(job, 'start')">{{ t('offers.start') }}</button><button v-if="job.status === 'IN_PROGRESS'" class="header-cta" type="button" @click="lifecycle(job, 'complete')">{{ t('offers.complete') }}</button></span></article></div><div class="offers-layout"><aside class="job-list"><p v-if="!jobs.length" class="job-empty">{{ t('offers.noOpenJobs') }}</p><button v-for="job in jobs" :key="job.id" type="button" class="job-list-item" :class="{ selected: selected?.id === job.id }" @click="select(job)"><strong>{{ job.title }}</strong><span>{{ job.city }} · {{ job.currency }} {{ job.budgetMin ?? '?' }}–{{ job.budgetMax ?? '?' }}</span></button></aside><div v-if="selected" class="offer-form"><h3>{{ selected.title }}</h3><p>{{ selected.description }}</p><form @submit.prevent="submit"><div class="job-fields"><label>{{ t('offers.price') }}<input v-model.number="form.price" required type="number" min="0" step="0.01"></label><label>{{ t('offers.currency') }}<select v-model="form.currency"><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option></select></label></div><label>{{ t('offers.message') }}<textarea v-model="form.message" required maxlength="4000" rows="3" /></label><div class="job-fields"><label>{{ t('offers.duration') }}<input v-model="form.estimatedDuration"></label><label>{{ t('offers.availableFrom') }}<input v-model="form.availableFrom" type="date"></label></div><button class="header-cta" :disabled="saving" type="submit">{{ t(editingId ? 'offers.update' : 'offers.submit') }}</button><span v-if="message" class="job-message">{{ message }}</span></form><div v-for="offer in offers" :key="offer.id" class="offer-row"><span><strong>{{ offer.price }} {{ offer.currency }}</strong> · {{ t(`offers.status.${offer.status.toLowerCase()}`) }}<small v-if="offer.estimatedDuration || offer.availableFrom"> · {{ offer.estimatedDuration || '' }} {{ offer.availableFrom || '' }}</small></span><button v-if="offer.status === 'PENDING'" class="job-secondary" type="button" @click="edit(offer)">{{ t('offers.edit') }}</button><button v-if="offer.status === 'PENDING'" class="job-danger" type="button" @click="withdraw(offer)">{{ t('offers.withdraw') }}</button></div></div></div></section>
</template>
