<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

interface Category { id: string; slug: string; icon: string | null; translations: Record<string, { name: string; description: string | null }> }
interface Provider { userId: string; displayName: string; description: string; city: string; postalCode: string; availabilityStatus: string; startingPrice: number | null; currency: string; services: { id: string; slug: string; translations: Record<string, { name: string }> }[]; rating?: { averageRating: number | null; reviewCount: number } }
interface Job { id: string; title: string; description: string; city: string; currency: string; budgetMin: number | null; budgetMax: number | null; category: Category }
interface Page<T> { items: T[]; page: number; pageSize: number; total: number; hasNext: boolean }
const props = defineProps<{ initialCategory?: string | null }>()
const { t, locale } = useI18n()
const query = ref(''); const city = ref(''); const category = ref(props.initialCategory ?? ''); const kind = ref('all'); const sort = ref('relevance'); const availability = ref(''); const minPrice = ref(''); const maxPrice = ref(''); const minRating = ref(''); const page = ref(1)
const providers = ref<Page<Provider>>({ items: [], page: 1, pageSize: 12, total: 0, hasNext: false }); const jobs = ref<Page<Job>>({ items: [], page: 1, pageSize: 12, total: 0, hasNext: false }); const categories = ref<Page<Category>>({ items: [], page: 1, pageSize: 12, total: 0, hasNext: false })
const loading = ref(false); const error = ref(false)
function categoryName(item: Category) { return item.translations[locale.value]?.name || item.translations.en?.name || item.slug }
function updateUrl() { const params = new URLSearchParams(); for (const [key, value] of Object.entries({ q: query.value, city: city.value, category: category.value, kind: kind.value, sort: sort.value, availability: availability.value, minPrice: minPrice.value, maxPrice: maxPrice.value, minRating: minRating.value, page: String(page.value) })) if (value && !(key === 'kind' && value === 'all') && !(key === 'sort' && value === 'relevance') && !(key === 'page' && value === '1')) params.set(key, value); const path = window.location.pathname.startsWith('/services/') ? window.location.pathname : '/search'; window.history.pushState({}, '', `${path}${params.toString() ? `?${params}` : ''}`) }
function readUrl() { const params = new URLSearchParams(window.location.search); query.value = params.get('q') ?? ''; city.value = params.get('city') ?? ''; category.value = params.get('category') ?? props.initialCategory ?? ''; kind.value = params.get('kind') ?? (props.initialCategory ? 'all' : 'all'); sort.value = params.get('sort') ?? 'relevance'; availability.value = params.get('availability') ?? ''; minPrice.value = params.get('minPrice') ?? ''; maxPrice.value = params.get('maxPrice') ?? ''; minRating.value = params.get('minRating') ?? ''; page.value = Math.max(1, Number(params.get('page') ?? '1') || 1) }
async function search(reset = false) { if (reset) page.value = 1; updateUrl(); loading.value = true; error.value = false; const params = new URLSearchParams(window.location.search); const response = await fetch(`/api/v1/search?${params}`); if (!response.ok) { error.value = true; loading.value = false; return }; const result = (await response.json() as { data: { providers: Page<Provider>; jobs: Page<Job>; categories: Page<Category> } }).data; providers.value = result.providers; jobs.value = result.jobs; categories.value = result.categories; loading.value = false }
function onPopState() { readUrl(); void search() }
onMounted(() => { readUrl(); void search(); window.addEventListener('popstate', onPopState) })
watch([kind, sort, availability], () => { if (!loading.value) void search(true) })
</script>

<template>
  <section class="content-section container search-page">
    <div class="section-heading"><div><span class="section-kicker">{{ t('search.kicker') }}</span><h2>{{ t('search.title') }}</h2><p>{{ t('search.description') }}</p></div></div>
    <form class="search-filters" @submit.prevent="search(true)"><input v-model="query" maxlength="120" :placeholder="t('search.query')"><input v-model="city" maxlength="120" :placeholder="t('search.city')"><select v-model="kind"><option value="all">{{ t('search.all') }}</option><option value="providers">{{ t('search.providers') }}</option><option value="jobs">{{ t('search.jobs') }}</option><option value="categories">{{ t('search.categories') }}</option></select><select v-model="sort"><option value="relevance">{{ t('search.relevance') }}</option><option value="newest">{{ t('search.newest') }}</option><option value="price">{{ t('search.price') }}</option></select><select v-model="availability"><option value="">{{ t('search.anyAvailability') }}</option><option value="AVAILABLE">{{ t('providers.online') }}</option><option value="BUSY">{{ t('search.busy') }}</option></select><input v-model="minPrice" inputmode="decimal" :placeholder="t('search.minPrice')"><input v-model="maxPrice" inputmode="decimal" :placeholder="t('search.maxPrice')"><select v-model="minRating"><option value="">{{ t('search.anyRating') }}</option><option v-for="rating in 5" :key="rating" :value="rating">{{ rating }}+ ★</option></select><button class="header-cta" type="submit">{{ t('search.apply') }}</button></form>
    <p v-if="loading" class="job-empty">{{ t('search.loading') }}</p>
    <p v-else-if="error" class="job-message">{{ t('search.error') }}</p>
    <template v-else>
      <div v-if="kind === 'all' || kind === 'categories'" class="search-result-section"><h3>{{ t('search.categories') }}</h3><div class="category-grid"><a v-for="item in categories.items" :key="item.id" class="category-card" :href="`/services/${item.slug}`"><div class="category-icon">{{ item.icon }}</div><div><h3>{{ categoryName(item) }}</h3><p>{{ item.translations[locale]?.description || item.translations.en?.description || '' }}</p></div></a></div><p v-if="!categories.items.length" class="job-empty">{{ t('search.empty') }}</p></div>
      <div v-if="kind === 'all' || kind === 'providers'" class="search-result-section"><h3>{{ t('search.providers') }}</h3><div class="provider-grid"><a v-for="item in providers.items" :key="item.userId" class="provider-card" :href="`/providers/${item.userId}`"><div class="provider-body"><h3>{{ item.displayName }}</h3><p>{{ item.city }} · {{ item.postalCode }}</p><p class="provider-rating">★ {{ item.rating?.averageRating ?? t('providers.ratingPending') }} · {{ item.rating?.reviewCount ?? 0 }} {{ t('providers.reviews') }}</p><small>{{ item.startingPrice === null ? t('providers.priceOnRequest') : `${item.startingPrice} ${item.currency}` }}</small></div></a></div><p v-if="!providers.items.length" class="job-empty">{{ t('search.empty') }}</p></div>
      <div v-if="kind === 'all' || kind === 'jobs'" class="search-result-section"><h3>{{ t('search.jobs') }}</h3><div class="job-list"><a v-for="item in jobs.items" :key="item.id" class="job-list-item" :href="`/jobs/${item.id}`"><strong>{{ item.title }}</strong><span>{{ item.city }} · {{ item.category.translations[locale]?.name || item.category.slug }}</span><small>{{ item.budgetMin ?? '?' }}–{{ item.budgetMax ?? '?' }} {{ item.currency }}</small></a></div><p v-if="!jobs.items.length" class="job-empty">{{ t('search.empty') }}</p></div>
      <div class="search-pagination"><button v-if="page > 1" class="job-secondary" type="button" @click="page--; search()">{{ t('search.previous') }}</button><span>{{ page }}</span><button v-if="(kind === 'providers' ? providers.hasNext : kind === 'jobs' ? jobs.hasNext : categories.hasNext)" class="job-secondary" type="button" @click="page++; search()">{{ t('search.next') }}</button></div>
    </template>
  </section>
</template>
