export default {
  brandTagline: 'Menschen. Hilfe. Nähe.',
  nav: { services: 'Dienstleistungen', customers: 'Für Kunden', providers: 'Für Anbieter', about: 'Über uns', help: 'Hilfe', login: 'Einloggen', register: 'Kostenlos registrieren' },
  hero: {
    free: '100% KOSTENLOS', title: 'Was brauchst du?', subtitle: 'Finde verifizierte Dienstleister in deiner Nähe.', servicePlaceholder: 'Beschreibe, was du brauchst ...', serviceHint: 'z. B. Reinigung, Elektriker, Umzug ...', location: 'PLZ oder Ort', locationHint: 'z. B. 88212 Ravensburg', findProviders: 'Anbieter finden', popular: 'Beliebt:', popularItems: { cleaning: 'Reinigung', electrician: 'Elektriker', gardening: 'Gartenarbeit', moving: 'Umzug', painter: 'Maler', car: 'Autoreparatur' }, benefitTitle: 'Für Kunden und Anbieter\nkostenlos', benefitSubtitle: 'Kostenlos für Kunden und Anbieter', verifiedProfiles: 'Verifizierte Profile', realReviews: 'Echte Bewertungen', directContact: 'Direkter Kontakt', nearby: 'In deiner Nähe', review: '„Endlich eine Plattform,\ndie einfach und fair ist!“', reviewAuthor: 'Kundin aus Ravensburg',
  },
  categories: { title: 'Alle Dienstleistungen', description: 'Entdecke unsere Kategorien.', showAll: 'Alle Kategorien anzeigen' },
  providers: { title: 'Empfohlene Dienstleister in deiner Nähe', description: 'Geprüft. Bewertet. Zuverlässig.', showAll: 'Alle anzeigen', online: 'Online', availableToday: 'Heute verfügbar', favorite: 'Favorit', reviews: 'Bewertungen', profile: 'Profil ansehen', items: { cleanTeam: { role: 'Haushaltsreinigung', tags: ['Haushaltsreinigung', 'Büroreinigung'], price: 'ab 24 € / Std.' }, mueller: { role: 'Handwerk & Montage', tags: ['Malerarbeiten', 'Trockenbau'], price: 'ab 35 € / Std.' }, greenPartner: { role: 'Garten & Landschaft', tags: ['Gartenarbeit', 'Heckenschnitt'], price: 'ab 28 € / Std.' }, schnellUmzug: { role: 'Umzug & Transport', tags: ['Umzug', 'Entrümpelung'], price: 'ab 45 € / Std.' } } },
  steps: { kicker: "SO EINFACH GEHT'S", title: 'In 4 Schritten zum Ziel', description: 'Einfach loslegen. Einfach helfen.', items: [{ title: 'Anfrage stellen', accent: 'Beschreibe, was du brauchst und wo.', description: 'Beschreibe, was du brauchst und wo.' }, { title: 'Passende Anbieter erhalten', accent: 'Passende Angebote erhalten', description: 'Wir finden geprüfte Dienstleister in deiner Nähe.' }, { title: 'Direkt kontaktieren', accent: 'Direkt kontaktieren', description: 'Schreibe oder rufe direkt an.' }, { title: 'Auftrag erledigt', accent: 'Der Auftrag ist erledigt', description: 'Bewerte den Service und hilf anderen.' }] },
  cta: { kicker: 'BEREIT?', title: "Gemeinsam geht's leichter.", description: 'Werde Teil von Helfio und mach den Unterschied.', register: 'Jetzt kostenlos registrieren' },
  footer: { tag: 'Marktplatz', description: 'Professionelle Dienstleistungen für Zuhause, Projekte und Alltag.', company: 'Unternehmen', service: 'Service', legal: 'Rechtliches', about: 'Über uns', careers: 'Karriere', partners: 'Partner', customerService: 'Kundenservice', help: 'Hilfe', reviews: 'Bewertungen', terms: 'AGB', privacy: 'Datenschutz', imprint: 'Impressum' },
} as const