export default {
  brandTagline: 'Menschen. Hilfe. Nähe.',
  nav: { services: 'Dienstleistungen', customers: 'Für Kunden', providers: 'Für Anbieter', about: 'Über uns', help: 'Hilfe', login: 'Einloggen', register: 'Kostenlos registrieren' },
  hero: {
    free: '100% KOSTENLOS', title: 'Was brauchst du?', subtitle: 'Finde verifizierte Dienstleister in deiner Nähe.', servicePlaceholder: 'Beschreibe, was du brauchst ...', serviceHint: 'z. B. Reinigung, Elektriker, Umzug ...', location: 'PLZ oder Ort', locationHint: 'z. B. 88212 Ravensburg', findProviders: 'Anbieter finden', popular: 'Beliebt:', popularItems: { cleaning: 'Reinigung', electrician: 'Elektriker', gardening: 'Gartenarbeit', moving: 'Umzug', painter: 'Maler', car: 'Autoreparatur' }, benefitTitle: 'Für Kunden und Anbieter\nkostenlos', benefitSubtitle: 'Kostenlos für Kunden und Anbieter', verifiedProfiles: 'Verifizierte Profile', realReviews: 'Echte Bewertungen', directContact: 'Direkter Kontakt', nearby: 'In deiner Nähe', review: '„Endlich eine Plattform,\ndie einfach und fair ist!“', reviewAuthor: 'Kundin aus Ravensburg',
  },
  categories: { title: 'Alle Dienstleistungen', description: 'Entdecke unsere Kategorien.', showAll: 'Alle Kategorien anzeigen' },
  providers: { title: 'Empfohlene Dienstleister in deiner Nähe', description: 'Geprüft. Bewertet. Zuverlässig.', showAll: 'Alle anzeigen', online: 'Online', availableToday: 'Heute verfügbar', favorite: 'Favorit', reviews: 'Bewertungen', profile: 'Profil ansehen', ratingPending: 'Offen', ratingPlaceholder: '(Bewertungen folgen)', priceOnRequest: 'Preis auf Anfrage', items: { cleanTeam: { role: 'Haushaltsreinigung', tags: ['Haushaltsreinigung', 'Büroreinigung'], price: 'ab 24 € / Std.' }, mueller: { role: 'Handwerk & Montage', tags: ['Malerarbeiten', 'Trockenbau'], price: 'ab 35 € / Std.' }, greenPartner: { role: 'Garten & Landschaft', tags: ['Gartenarbeit', 'Heckenschnitt'], price: 'ab 28 € / Std.' }, schnellUmzug: { role: 'Umzug & Transport', tags: ['Umzug', 'Entrümpelung'], price: 'ab 45 € / Std.' } } },
  steps: { kicker: "SO EINFACH GEHT'S", title: 'In 4 Schritten zum Ziel', description: 'Einfach loslegen. Einfach helfen.', items: [{ title: 'Anfrage stellen', accent: 'Beschreibe, was du brauchst und wo.', description: 'Beschreibe, was du brauchst und wo.' }, { title: 'Passende Anbieter erhalten', accent: 'Passende Angebote erhalten', description: 'Wir finden geprüfte Dienstleister in deiner Nähe.' }, { title: 'Direkt kontaktieren', accent: 'Direkt kontaktieren', description: 'Schreibe oder rufe direkt an.' }, { title: 'Auftrag erledigt', accent: 'Der Auftrag ist erledigt', description: 'Bewerte den Service und hilf anderen.' }] },
  cta: { kicker: 'BEREIT?', title: "Gemeinsam geht's leichter.", description: 'Werde Teil von Helfio und mach den Unterschied.', register: 'Jetzt kostenlos registrieren' },
  auth: { login: 'Einloggen', register: 'Registrieren', logout: 'Ausloggen', account: 'Konto' },
  providerProfile: { kicker: 'ANBIETERPROFIL', title: 'Erstelle dein professionelles Profil', description: 'Zeige Kunden, was du anbietest und wo du arbeitest.', name: 'Anzeigename', about: 'Über deinen Service', city: 'Stadt', postalCode: 'PLZ', radius: 'Aktionsradius (km)', experience: 'Berufserfahrung in Jahren', startingPrice: 'Startpreis', availability: 'Verfügbarkeit', available: 'Verfügbar', busy: 'Ausgelastet', unavailable: 'Nicht verfügbar', services: 'Dienstleistungen', publicProfile: 'Profil öffentlich anzeigen', save: 'Profil speichern', saving: 'Speichern...', saved: 'Profil gespeichert.', saveError: 'Profil konnte nicht gespeichert werden.', serviceError: 'Dienstleistungen konnten nicht gespeichert werden.' },
  jobs: { kicker: 'KUNDENANFRAGEN', title: 'Deine Anfragen', description: 'Beschreibe einen Auftrag und veröffentliche ihn, wenn du bereit bist.', newRequest: 'Neue Anfrage', empty: 'Du hast noch keine Anfragen.', create: 'Anfrage erstellen', edit: 'Anfrage bearbeiten', category: 'Kategorie', chooseCategory: 'Kategorie auswählen', titleField: 'Titel', descriptionField: 'Beschreibung', city: 'Stadt', postalCode: 'PLZ', country: 'Ländercode', budgetType: 'Budgettyp', range: 'Budgetrahmen', fixed: 'Festes Budget', negotiable: 'Verhandelbar', minimum: 'Minimum', maximum: 'Maximum', currency: 'Währung', preferredDate: 'Wunschtermin', preferredTime: 'Wunschzeit', saveDraft: 'Anfrage speichern', saving: 'Speichern...', publish: 'Anfrage veröffentlichen', cancel: 'Anfrage stornieren', saved: 'Anfrage gespeichert.', published: 'Anfrage veröffentlicht.', cancelled: 'Anfrage storniert.', saveError: 'Anfrage konnte nicht gespeichert werden.', transitionError: 'Status konnte nicht geändert werden.', status: { draft: 'Entwurf', open: 'Offen', assigned: 'Zugewiesen', in_progress: 'In Bearbeitung', completed: 'Abgeschlossen', cancelled: 'Storniert' } },
  offers: { providerKicker: 'OFFENE AUFTRÄGE', providerTitle: 'Aufträge finden und Angebote senden', providerDescription: 'Offene Kundenanfragen durchsuchen und Angebot abgeben.', noOpenJobs: 'Keine offenen Aufträge.', price: 'Preis', currency: 'Währung', message: 'Nachricht', duration: 'Dauer', availableFrom: 'Verfügbar ab', submit: 'Angebot senden', submitted: 'Angebot gesendet.', submitError: 'Angebot konnte nicht gesendet werden.', withdraw: 'Zurückziehen', customerKicker: 'ANGEBOTE', customerTitle: 'Angebote für deine Anfragen', customerDescription: 'Anbieter vergleichen und Angebot auswählen.', noJobs: 'Noch keine Anfragen.', noOffers: 'Noch keine Angebote.', provider: 'Anbieter', years: 'Jahre Erfahrung', accept: 'Annehmen', reject: 'Ablehnen' },
  assistant: { title: 'Helfio Assistent', greeting: 'Wie kann ich bei Helfio helfen?', placeholder: 'Frage zu Services, Aufträgen oder Anbietern...', send: 'Senden', open: 'Helfio Assistent öffnen', close: 'Helfio Assistent schließen', unavailable: 'Der Assistent ist vorübergehend nicht verfügbar.' },
  footer: { tag: 'Marktplatz', description: 'Professionelle Dienstleistungen für Zuhause, Projekte und Alltag.', company: 'Unternehmen', service: 'Service', legal: 'Rechtliches', about: 'Über uns', careers: 'Karriere', partners: 'Partner', customerService: 'Kundenservice', help: 'Hilfe', reviews: 'Bewertungen', terms: 'AGB', privacy: 'Datenschutz', imprint: 'Impressum' },
} as const