export default {
  brandTagline: 'Njerëz. Ndihmë. Afër.',
  nav: { services: 'Shërbime', customers: 'Për klientët', providers: 'Për ofruesit', about: 'Rreth nesh', help: 'Ndihmë', login: 'Hyr', register: 'Regjistrohu falas' },
  hero: {
    free: '100% FALAS', title: 'Çfarë ndihme të duhet?', subtitle: 'Gjej profesionistë të verifikuar pranë teje.', servicePlaceholder: 'Përshkruaj çfarë të duhet ...', serviceHint: 'p.sh. pastrim, elektricist, zhvendosje ...', location: 'Kodi postar ose qyteti', locationHint: 'p.sh. 88212 Ravensburg', findProviders: 'Gjej profesionistë', popular: 'Të njohura:', popularItems: { cleaning: 'Pastrim', electrician: 'Elektricist', gardening: 'Kopshtari', moving: 'Zhvendosje', painter: 'Lyerje', car: 'Riparim automjeti' }, benefitTitle: 'Për klientët dhe ofruesit\nfalas', benefitSubtitle: 'Falas për klientët dhe ofruesit', verifiedProfiles: 'Profile të verifikuara', realReviews: 'Vlerësime të vërteta', directContact: 'Kontakt i drejtpërdrejtë', nearby: 'Pranë teje', review: '„Më në fund një platformë\ne thjeshtë dhe e drejtë!“', reviewAuthor: 'Kliente nga Ravensburgu',
  },
  categories: { title: 'Të gjitha shërbimet', description: 'Zbulo kategoritë tona.', showAll: 'Shiko të gjitha kategoritë' },
  providers: { title: 'Ofrues të rekomanduar pranë teje', description: 'Të verifikuar. Të vlerësuar. Të besueshëm.', showAll: 'Shiko të gjitha', online: 'Online', availableToday: 'Në dispozicion sot', favorite: 'I preferuar', reviews: 'vlerësime', profile: 'Shiko profilin', items: { cleanTeam: { role: 'Pastrim shtëpie', tags: ['Pastrim shtëpie', 'Pastrim zyrash'], price: 'nga 24 € / orë' }, mueller: { role: 'Punime dhe montim', tags: ['Punime lyerjeje', 'Gips'], price: 'nga 35 € / orë' }, greenPartner: { role: 'Kopsht dhe peizazh', tags: ['Kopshtari', 'Krasitje gardhi'], price: 'nga 28 € / orë' }, schnellUmzug: { role: 'Zhvendosje dhe transport', tags: ['Zhvendosje', 'Pastrimi i objekteve'], price: 'nga 45 € / orë' } } },
  steps: { kicker: 'KAQ E LEHTË ËSHTË', title: 'Arrije qëllimin në 4 hapa', description: 'Fillo thjesht. Ndihmo thjesht.', items: [{ title: 'Dërgo një kërkesë', accent: 'Përshkruaj çfarë të duhet dhe ku.', description: 'Përshkruaj çfarë të duhet dhe ku.' }, { title: 'Merr ofrues të përshtatshëm', accent: 'Merr oferta të përshtatshme', description: 'Gjejmë profesionistë të verifikuar pranë teje.' }, { title: 'Kontakto drejtpërdrejt', accent: 'Kontakto drejtpërdrejt', description: 'Shkruaj ose telefono direkt.' }, { title: 'Puna u krye', accent: 'Puna përfundoi', description: 'Vlerëso shërbimin dhe ndihmo të tjerët.' }] },
  cta: { kicker: 'GATI?', title: 'Së bashku është më lehtë.', description: 'Bëhu pjesë e Helfio dhe bëj ndryshimin.', register: 'Regjistrohu falas tani' },
  footer: { tag: 'Treg', description: 'Shërbime profesionale për shtëpinë, projektet dhe jetën e përditshme.', company: 'Kompania', service: 'Shërbimi', legal: 'Ligjore', about: 'Rreth nesh', careers: 'Karriera', partners: 'Partnerët', customerService: 'Shërbimi ndaj klientit', help: 'Ndihmë', reviews: 'Vlerësime', terms: 'Kushtet', privacy: 'Privatësia', imprint: 'Njoftim ligjor' },
} as const