export default {
  brandTagline: 'Njerëz. Ndihmë. Afër.',
  nav: { services: 'Shërbime', customers: 'Për klientët', providers: 'Për ofruesit', about: 'Rreth nesh', help: 'Ndihmë', login: 'Hyr', register: 'Regjistrohu falas' },
  hero: {
    free: '100% FALAS', title: 'Çfarë ndihme të duhet?', subtitle: 'Gjej profesionistë të verifikuar pranë teje.', servicePlaceholder: 'Përshkruaj çfarë të duhet ...', serviceHint: 'p.sh. pastrim, elektricist, zhvendosje ...', location: 'Kodi postar ose qyteti', locationHint: 'p.sh. 88212 Ravensburg', findProviders: 'Gjej profesionistë', popular: 'Të njohura:', popularItems: { cleaning: 'Pastrim', electrician: 'Elektricist', gardening: 'Kopshtari', moving: 'Zhvendosje', painter: 'Lyerje', car: 'Riparim automjeti' }, benefitTitle: 'Për klientët dhe ofruesit\nfalas', benefitSubtitle: 'Falas për klientët dhe ofruesit', verifiedProfiles: 'Profile të verifikuara', realReviews: 'Vlerësime të vërteta', directContact: 'Kontakt i drejtpërdrejtë', nearby: 'Pranë teje', review: '„Më në fund një platformë\ne thjeshtë dhe e drejtë!“', reviewAuthor: 'Kliente nga Ravensburgu',
  },
  categories: { title: 'Të gjitha shërbimet', description: 'Zbulo kategoritë tona.', showAll: 'Shiko të gjitha kategoritë' },
  providers: { title: 'Ofrues të rekomanduar pranë teje', description: 'Të verifikuar. Të vlerësuar. Të besueshëm.', showAll: 'Shiko të gjitha', online: 'Online', availableToday: 'Në dispozicion sot', favorite: 'I preferuar', reviews: 'vlerësime', profile: 'Shiko profilin', ratingPending: 'Në pritje', ratingPlaceholder: '(vlerësimet do të vijnë)', priceOnRequest: 'Çmimi sipas kërkesës', items: { cleanTeam: { role: 'Pastrim shtëpie', tags: ['Pastrim shtëpie', 'Pastrim zyrash'], price: 'nga 24 € / orë' }, mueller: { role: 'Punime dhe montim', tags: ['Punime lyerjeje', 'Gips'], price: 'nga 35 € / orë' }, greenPartner: { role: 'Kopsht dhe peizazh', tags: ['Kopshtari', 'Krasitje gardhi'], price: 'nga 28 € / orë' }, schnellUmzug: { role: 'Zhvendosje dhe transport', tags: ['Zhvendosje', 'Pastrimi i objekteve'], price: 'nga 45 € / orë' } } },
  steps: { kicker: 'KAQ E LEHTË ËSHTË', title: 'Arrije qëllimin në 4 hapa', description: 'Fillo thjesht. Ndihmo thjesht.', items: [{ title: 'Dërgo një kërkesë', accent: 'Përshkruaj çfarë të duhet dhe ku.', description: 'Përshkruaj çfarë të duhet dhe ku.' }, { title: 'Merr ofrues të përshtatshëm', accent: 'Merr oferta të përshtatshme', description: 'Gjejmë profesionistë të verifikuar pranë teje.' }, { title: 'Kontakto drejtpërdrejt', accent: 'Kontakto drejtpërdrejt', description: 'Shkruaj ose telefono direkt.' }, { title: 'Puna u krye', accent: 'Puna përfundoi', description: 'Vlerëso shërbimin dhe ndihmo të tjerët.' }] },
  cta: { kicker: 'GATI?', title: 'Së bashku është më lehtë.', description: 'Bëhu pjesë e Helfio dhe bëj ndryshimin.', register: 'Regjistrohu falas tani' },
  auth: { login: 'Hyr', register: 'Regjistrohu', logout: 'Dil', account: 'Llogaria' },
  providerProfile: { kicker: 'PROFILI I OFRUESIT', title: 'Krijo profilin tënd profesional', description: 'Tregoju klientëve çfarë ofron dhe ku punon.', name: 'Emri i shfaqur', about: 'Rreth shërbimit', city: 'Qyteti', postalCode: 'Kodi postar', radius: 'Rrezja e shërbimit (km)', experience: 'Vitet e përvojës', startingPrice: 'Çmimi fillestar', availability: 'Disponueshmëria', available: 'I disponueshëm', busy: 'I zënë', unavailable: 'I padisponueshëm', services: 'Shërbimet', publicProfile: 'Bëje profilin publik', save: 'Ruaj profilin', saving: 'Duke ruajtur...', saved: 'Profili u ruajt.', saveError: 'Profili nuk u ruajt.', serviceError: 'Shërbimet nuk u ruajtën.' },
  jobs: { kicker: 'KËRKESAT E KLIENTIT', title: 'Kërkesat e tua', description: 'Përshkruaj një punë dhe publikoje kur të jesh gati.', newRequest: 'Kërkesë e re', empty: 'Nuk ke ende kërkesa.', create: 'Krijo kërkesë', edit: 'Ndrysho kërkesën', category: 'Kategoria', chooseCategory: 'Zgjidh kategorinë', titleField: 'Titulli', descriptionField: 'Përshkrimi', city: 'Qyteti', postalCode: 'Kodi postar', country: 'Kodi i shtetit', budgetType: 'Lloji i buxhetit', range: 'Interval buxheti', fixed: 'Buxhet fiks', negotiable: 'I negociueshëm', minimum: 'Minimumi', maximum: 'Maksimumi', currency: 'Monedha', preferredDate: 'Data e preferuar', preferredTime: 'Koha e preferuar', saveDraft: 'Ruaj kërkesën', saving: 'Duke ruajtur...', publish: 'Publiko kërkesën', cancel: 'Anulo kërkesën', saved: 'Kërkesa u ruajt.', published: 'Kërkesa u publikua.', cancelled: 'Kërkesa u anulua.', saveError: 'Kërkesa nuk u ruajt.', transitionError: 'Statusi nuk u ndryshua.', status: { draft: 'Draft', open: 'E hapur', assigned: 'Caktuar', in_progress: 'Në proces', completed: 'Përfunduar', cancelled: 'Anuluar' } },
  footer: { tag: 'Treg', description: 'Shërbime profesionale për shtëpinë, projektet dhe jetën e përditshme.', company: 'Kompania', service: 'Shërbimi', legal: 'Ligjore', about: 'Rreth nesh', careers: 'Karriera', partners: 'Partnerët', customerService: 'Shërbimi ndaj klientit', help: 'Ndihmë', reviews: 'Vlerësime', terms: 'Kushtet', privacy: 'Privatësia', imprint: 'Njoftim ligjor' },
} as const