export default {
  brandTagline: 'İnsanlar. Yardım. Yakınlık.',
  nav: { services: 'Hizmetler', customers: 'Müşteriler için', providers: 'Hizmet verenler için', about: 'Hakkımızda', help: 'Yardım', login: 'Giriş yap', register: 'Ücretsiz kayıt ol' },
  hero: {
    free: '%100 ÜCRETSİZ', title: 'Neye ihtiyacın var?', subtitle: 'Yakınındaki doğrulanmış hizmet sağlayıcılarını bul.', servicePlaceholder: 'İhtiyacını açıkla ...', serviceHint: 'örn. temizlik, elektrikçi, taşınma ...', location: 'Posta kodu veya şehir', locationHint: 'örn. 88212 Ravensburg', findProviders: 'Hizmet sağlayıcı bul', popular: 'Popüler:', popularItems: { cleaning: 'Temizlik', electrician: 'Elektrikçi', gardening: 'Bahçe işi', moving: 'Taşınma', painter: 'Boyacı', car: 'Oto tamiri' }, benefitTitle: 'Müşteriler ve hizmet verenler\niçin ücretsiz', benefitSubtitle: 'Müşteriler ve hizmet verenler için ücretsiz', verifiedProfiles: 'Doğrulanmış profiller', realReviews: 'Gerçek değerlendirmeler', directContact: 'Doğrudan iletişim', nearby: 'Yakınında', review: '„Sonunda basit ve\nadil bir platform!“', reviewAuthor: 'Ravensburg’dan müşteri',
  },
  categories: { title: 'Tüm hizmetler', description: 'Kategorilerimizi keşfet.', showAll: 'Tüm kategorileri göster' },
  providers: { title: 'Yakınındaki önerilen hizmet sağlayıcıları', description: 'Doğrulanmış. Değerlendirilmiş. Güvenilir.', showAll: 'Tümünü göster', online: 'Çevrimiçi', availableToday: 'Bugün müsait', favorite: 'Favori', reviews: 'değerlendirme', profile: 'Profili gör', items: { cleanTeam: { role: 'Ev temizliği', tags: ['Ev temizliği', 'Ofis temizliği'], price: 'saatlik 24 €’dan başlayan' }, mueller: { role: 'Zanaat ve montaj', tags: ['Boyama işleri', 'Alçıpan'], price: 'saatlik 35 €’dan başlayan' }, greenPartner: { role: 'Bahçe ve peyzaj', tags: ['Bahçe işi', 'Çit budama'], price: 'saatlik 28 €’dan başlayan' }, schnellUmzug: { role: 'Taşınma ve nakliye', tags: ['Taşınma', 'Eşya boşaltma'], price: 'saatlik 45 €’dan başlayan' } } },
  steps: { kicker: 'BU KADAR KOLAY', title: 'Hedefine 4 adımda ulaş', description: 'Hemen başla. Yardım et.', items: [{ title: 'Talep gönder', accent: 'Neye ve nerede ihtiyacın olduğunu anlat.', description: 'Neye ve nerede ihtiyacın olduğunu açıkla.' }, { title: 'Uygun hizmet verenleri al', accent: 'Uygun teklifler al', description: 'Yakınındaki doğrulanmış hizmet sağlayıcılarını buluruz.' }, { title: 'Doğrudan iletişime geç', accent: 'Doğrudan iletişime geç', description: 'Doğrudan yaz veya ara.' }, { title: 'İş tamamlandı', accent: 'İş tamamlandı', description: 'Hizmeti değerlendir ve başkalarına yardım et.' }] },
  cta: { kicker: 'HAZIR MISIN?', title: 'Birlikte daha kolay.', description: 'Helfio’ya katıl ve fark yarat.', register: 'Şimdi ücretsiz kayıt ol' },
  footer: { tag: 'Pazar yeri', description: 'Ev, projeler ve günlük yaşam için profesyonel hizmetler.', company: 'Şirket', service: 'Hizmet', legal: 'Yasal', about: 'Hakkımızda', careers: 'Kariyer', partners: 'Ortaklar', customerService: 'Müşteri hizmetleri', help: 'Yardım', reviews: 'Değerlendirmeler', terms: 'Koşullar', privacy: 'Gizlilik', imprint: 'Yasal bildirim' },
} as const