<script setup lang="ts">
import { onMounted, ref } from 'vue'
import AppHeader from './components/AppHeader.vue'
import heroImage from '../file_00000000f89881f4b0b5376aeda919f8.png'

type Locale = 'de' | 'sq'
interface CategoryNode {
	slug: string
	icon: string | null
	sortOrder: number
	createdAt: string
	updatedAt: string
	translations: Record<string, { name: string; description: string | null }>
	children: CategoryNode[]
}

const locale = ref<Locale>('de')
const categories = ref<CategoryNode[]>([])
const providers = [{name:'CleanTeam',role:'Haushaltsreinigung',location:'Ravensburg · 2 km',rating:'4.9',reviews:'124',price:'ab 24 € / Std.',initials:'CT',tone:'provider-mint',online:true,tags:['Haushaltsreinigung','Büroreinigung']},{name:'Müller Handwerk',role:'Handwerk & Montage',location:'Weingarten · 5 km',rating:'4.8',reviews:'98',price:'ab 35 € / Std.',initials:'MH',tone:'provider-blue',online:false,tags:['Malerarbeiten','Trockenbau']},{name:'GrünPartner',role:'Garten & Landschaft',location:'Ravensburg · 3 km',rating:'4.9',reviews:'76',price:'ab 28 € / Std.',initials:'GP',tone:'provider-green',online:true,tags:['Gartenarbeit','Heckenschnitt']},{name:'SchnellUmzug',role:'Umzug & Transport',location:'Friedrichshafen · 12 km',rating:'4.7',reviews:'62',price:'ab 45 € / Std.',initials:'SU',tone:'provider-peach',online:true,tags:['Umzug','Entrümpelung']}]
const steps = [['01','Anfrage stellen','Bëj një kërkesë','Beschreibe, was du brauchst und wo. Përshkruaj çfarë të duhet dhe ku.'],['02','Passende Anbieter erhalten','Merr oferta të përshtatshme','Wir finden geprüfte Dienstleister in deiner Nähe.'],['03','Direkt kontaktieren','Kontakto direkt','Schreibe oder rufe direkt an. Shkruaj ose telefono direkt.'],['04','Auftrag erledigt','Puna u krye','Bewerte den Service und hilf anderen.']]
function changeLocale(next: Locale) { locale.value = next }
onMounted(async () => {
	const response = await fetch('/api/v1/categories/homepage')
	if (!response.ok) return
	const payload = await response.json() as { data: CategoryNode[] }
	categories.value = payload.data
})
</script>
<template><div class="page-shell"><AppHeader :locale="locale" @change-locale="changeLocale" /><main>
<section class="hero-section"><div class="hero-media" :style="{ backgroundImage: `url(${heroImage})` }" aria-hidden="true" /><div class="hero-shade" /><div class="container hero-inner"><div class="hero-copy"><span class="free-badge">100% KOSTENLOS / 100% FALAS</span><h1>Was brauchst du?<br><em>Çfarë ndihme të duhet?</em></h1><p>Finde verifizierte Dienstleister in deiner Nähe.<br>Gjej profesionistë të verifikuar pranë teje.</p><div class="search-box"><div class="search-field"><span class="search-icon">⌕</span><div><strong>Beschreibe, was du brauchst ...</strong><small>Përshkruaj çfarë të duhet ...<br>z. B. Reinigung, Elektriker, Umzug ...</small></div></div><div class="search-separator" /><div class="search-field location"><span class="search-icon">⌖</span><div><strong>PLZ oder Ort</strong><small>Kodi postar ose qyteti<br>z. B. 88212 Ravensburg</small></div></div><button class="search-submit" type="button">⌕ <span>Anbieter finden<br><small>Gjej profesionistë</small></span></button></div><div class="popular"><span>Beliebt:</span><button type="button">Reinigung</button><button type="button">Elektriker</button><button type="button">Gartenarbeit</button><button type="button">Umzug</button><button type="button">Maler</button><button type="button">Autoreparatur</button></div></div><aside class="hero-aside"><div class="benefit-card"><strong>👥 &nbsp; Für Kunden und Anbieter<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kostenlos</strong><p>Falas për klientët dhe ofruesit</p><div class="benefit-line"><span>✓</span> Verifizierte Profile<br><small>Profile të verifikuara</small></div><div class="benefit-line"><span>★</span> Echte Bewertungen<br><small>Vlerësime të vërteta</small></div><div class="benefit-line"><span>▢</span> Direkter Kontakt<br><small>Kontakt i drejtpërdrejtë</small></div><div class="benefit-line"><span>●</span> In deiner Nähe<br><small>Pranë teje</small></div></div><div class="review-card"><strong>„Endlich eine Plattform,<br>die einfach und fair ist!“</strong><span>★★★★★ &nbsp; – Kundin aus Ravensburg</span></div></aside></div></section>
<section class="content-section container"><div class="section-heading"><div><h2>Alle Dienstleistungen</h2><p>Entdecke unsere Kategorien. Zbulo kategoritë tona.</p></div><a href="#">Alle Kategorien anzeigen<br>Shiko të gjitha kategoritë <span>→</span></a></div><div class="category-grid"><article v-for="category in categories" :key="category.slug" class="category-card"><div class="category-icon" :class="`icon-${['mint','orange','green','blue','red','blue','pink','yellow','blue','purple','orange','slate'][(category.sortOrder / 10) - 1]}`">{{ category.icon }}</div><div><h3>{{ category.translations.de?.name }}</h3><p>{{ category.translations.sq?.name }}</p></div></article></div></section>
<section class="content-section providers-section container"><div class="section-heading"><div><h2>Empfohlene Dienstleister in deiner Nähe</h2><p>Geprüft. Bewertet. Zuverlässig. Të verifikuar. Të vlerësuar. Të besueshëm.</p></div><a href="#">Alle anzeigen <span>→</span></a></div><div class="provider-grid"><article v-for="provider in providers" :key="provider.name" class="provider-card"><div class="provider-photo" :class="provider.tone" :style="{ backgroundImage: `url(${heroImage})` }"><span>{{ provider.initials }}</span><i :class="{ offline: !provider.online }">{{ provider.online ? '● Online' : '● Heute verfügbar' }}</i><button type="button" aria-label="Favorit">♡</button></div><div class="provider-body"><div class="provider-name-row"><div><h3>{{ provider.name }}</h3></div></div><div class="provider-rating">★ {{ provider.rating }} <span>({{ provider.reviews }} Bewertungen)</span></div><div class="provider-details"><span>⌖ {{ provider.location }}</span></div><div class="provider-tags"><span v-for="tag in provider.tags" :key="tag">{{ tag }}</span></div><div class="provider-footer"><strong>{{ provider.price }}</strong><button type="button">Profil ansehen</button></div></div></article></div></section>
<section class="steps-section"><div class="container"><div class="section-heading centered"><div><span class="section-kicker">SO EINFACH GEHT'S</span><h2>In 4 Schritten zum Ziel</h2><p>Einfach loslegen. Einfach helfen.</p></div></div><div class="steps-grid"><article v-for="step in steps" :key="step[0]" class="step"><span class="step-number">{{ step[0] }}</span><div class="step-symbol">{{ step[0] === '01' ? '⌕' : step[0] === '02' ? '♧' : step[0] === '03' ? '♡' : '✓' }}</div><h3>{{ step[1] }}</h3><strong>{{ step[2] }}</strong><p>{{ step[3] }}</p></article></div></div></section><section class="cta-section container"><div class="cta-mark">✦</div><div><span class="section-kicker">BEREIT?</span><h2>Gemeinsam geht's leichter.</h2><p>Werde Teil von Helfio und mach den Unterschied.</p></div><button class="cta-button" type="button">Jetzt kostenlos registrieren <span>→</span></button></section>
</main></div></template>
